apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  policies:
  - name: rate-limit-jwt-gold
  - name: rate-limit-jwt-silver
  - name: rate-limit-jwt-bronze
  routes:
  - path: /tea
    route: cafe/tea
  - path: /coffee
    route: cafe/coffee
