apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  # policies:
  # - name: rate-limit-jwt-gold
  # - name: rate-limit-jwt-silver
  # - name: rate-limit-jwt-bronze
  routes:
  - path: /tea
    route: default/tea
  - path: /coffee
    route: default/coffee
