apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  policies:
  - name: rate-limit-jwt-premium
  - name: rate-limit-jwt-basic
  routes:
  - path: /coffee
    action:
      pass: coffee
