apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee
    # policies:
    # - name: rate-limit-jwt-gold
    # - name: rate-limit-jwt-silver
    # - name: rate-limit-jwt-bronze
