apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-gold
spec:
  rateLimit:
    rate: 20r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Gold
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-silver
spec:
  rateLimit:
    rate: 10r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Silver
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-bronze
spec:
  rateLimit:
    rate: 1r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Bronze
      default: true
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-gold2
spec:
  rateLimit:
    rate: 25r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Gold
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-silver2
spec:
  rateLimit:
    rate: 15r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Silver
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-jwt-bronze2
spec:
  rateLimit:
    rate: 2r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    logLevel: info
    condition:
      jwt:
        claim: consumer_group.tier
        match: Bronze
      default: true
