apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea
spec:
  host: cafe.example.com
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  subroutes:
  - path: /tea
    action:
      pass: tea
    policies:
    - name: rate-limit-jwt-gold
    - name: rate-limit-jwt-silver
    - name: rate-limit-jwt-bronze
