controller:
  name: controller
  kind: deployment
  nginxplus: true
  image:
    repository: private-registry.nginx.com/nginx-ic/nginx-plus-ingress
  serviceAccount:
    imagePullSecretName: nginx-registry-credentials
