name: Run Smoke Tests
description: Run Smoke Tests for the project

inputs:
  k8s-version:
    description: Kubernetes version to use
    required: false
  k8s-timeout:
    description: Timeout to use
    default: 75s
    required: false
  image-type:
    description: Image type to test
    required: true
  image-name:
    description: Docker image name to test
    required: true
  tag:
    description: Docker image tag to test
    required: true
  test-image:
    description: Test Docker image to use
    default: gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:latest
    required: false
  marker:
    description: Marker to use
    required: false
  label:
    description: Label for test
    required: false
  registry-token:
    description: JWT token for accessing container registry
    required: false
  plus-jwt:
    description: JWT for NGINX Plus
    required: false

outputs:
  test-results-name:
    description: Test results name
    value: ${{ steps.k8s.outputs.test_name }}
  test-results-path:
    description: Test results full path
    value: ${{ steps.k8s.outputs.test_output_path }}

runs:
  using: composite
  steps:
    - name: Deploy Kubernetes
      id: k8s
      run: |
        make -f tests/Makefile create-mini-cluster K8S_CLUSTER_VERSION=v${{ inputs.k8s-version }} K8S_TIMEOUT=${{ inputs.k8s-timeout }}
        echo "Kubernetes cluster created with version v${{ inputs.k8s-version }} and timeout ${{ inputs.k8s-timeout }}"
        minikube image load ${{ inputs.image-name }}:${{ inputs.tag }}
        echo "Docker image ${{ inputs.image-name }}:${{ inputs.tag }} loaded into Minikube cluster"
        label="${{ inputs.label }}"
        nospaces="${label// /_}"
        noslash="${nospaces//\//_}"
        sanitized_marker="${noslash//\'/}"
        name="${sanitized_marker}-${{ inputs.k8s-version }}"
        cluster_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minikube)
        test_name=tests-nginx-${{ inputs.image-type }}-${name}.html
        test_output_path=${{ github.workspace }}/tests/${test_name}
        echo "cluster_ip=${cluster_ip}" >> $GITHUB_OUTPUT
        echo "test_name=${test_name}" >> $GITHUB_OUTPUT
        echo "test_output_path=${test_output_path}" >> $GITHUB_OUTPUT
        echo "Output:"
        echo "  cluster_ip=${cluster_ip}"
        echo "  test_output_path=${test_output_path}"
      shell: bash

    # - name: Setup Kubeconfig
    #   run: |
    #     sed -i 's|server:.*|server: https://${{ steps.k8s.outputs.cluster_ip }}:6443|' ~/.kube/kind/config
    #   shell: bash

    - name: Run Smoke Tests
      id: smoke-tests
      run: |
        touch ${{ steps.k8s.outputs.test_output_path }}
        find /root -ls
        docker run --rm \
        --name test-runner-${{ github.run_id }} \
        --network=minikube \
        -v "/var/run/docker.sock:/var/run/docker.sock" \
        -v ~/.docker:/root/.docker \
        -v ${{ github.workspace }}/tests:/workspace/tests \
        -v ${{ github.workspace }}/common-secrets:/workspace/common-secrets \
        -v ${{ github.workspace }}/deployments:/workspace/deployments \
        -v ${{ github.workspace }}/charts:/workspace/charts \
        -v ${{ github.workspace }}/config:/workspace/config \
        -v ${{ github.workspace }}/pyproject.toml:/workspace/pyproject.toml \
        -v ${{ steps.k8s.outputs.test_output_path }}:${{ steps.k8s.outputs.test_output_path }} \
        -v $HOME/.minikube:$HOME/.minikube \
        ${{ inputs.test-image }} \
        --docker-registry-user=oauth2accesstoken \
        --docker-registry-token=${{ inputs.registry-token }} \
        --kubeconfig=/root/.kube/config \
        --context=minikube \
        --image=${{ inputs.image-name }}:${{ inputs.tag }} \
        --image-pull-policy=Never \
        --ic-type=nginx${{ contains(inputs.image-type, 'plus') && '-plus' || '' }}-ingress \
        --service=nodeport \
        --node-ip=minikube \
        --html=${{ steps.k8s.outputs.test_output_path }} \
        --self-contained-html \
        --durations=10 \
        --show-ic-logs=yes \
        --plus-jwt=${{ inputs.plus-jwt }} \
        -m ${{ inputs.marker != '' && inputs.marker || '""' }}
      working-directory: ./tests
      shell: bash
