version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /build
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /tests/docker
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /perf-tests
    schedule:
      interval: daily

# update go dependencies for release branch
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: release-3.0
    ignore:
      - dependency-name: "*"
        update-types:
        - version-update:semver-minor
        - version-update:semver-major
