changelog:
  exclude:
    labels:
      - skip changelog
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 💣 Breaking Changes
      labels:
        - change
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📦 Helm Chart
      labels:
        - helm_chart
    - title: 🧪 Tests
      labels:
        - tests
    - title: 🔨 Maintenance
      labels:
        - chore
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
