linters-settings:
  misspell:
    locale: US

linters:
    enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    disable-all: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
