language: go

sudo: required
services:
 - docker
env:
 - GO15VENDOREXPERIMENT=1
go:
 - 1.8.3 
script: 
 - cd nginx-controller && make clean && make PREFIX=gcr.io/nginx-ic-dev/nginx-ingress VERSION=0.9.0 BUILD_IN_CONTAINER=1 PUSH_TO_GCR=1
