language: go
sudo: required
services:
- docker
go:
- 1.8.3
deploy:
  provider: gae
  project: nginx-ic-dev
  keyfile: client-secret.json
script:
- cd nginx-controller && make clean && make PREFIX=gcr.io/nginx-ic-dev/nginx-ingress
  VERSION=0.9.0 BUILD_IN_CONTAINER=1 PUSH_TO_GCR=1
before_install:
- openssl aes-256-cbc -K $encrypted_93342ace2b30_key -iv $encrypted_93342ace2b30_iv
  -in client-secret.json.enc -out client-secret.json -d
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project nginx-ic-dev
