language: go
sudo: required
services:
- docker
go:
- 1.8.3
script:
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ] ; then export VERSION=pr-${TRAVIS_PULL_REQUEST}-${TRAVIS_BUILD_NUMBER};
  else export VERSION=${TRAVIS_COMMIT} ; fi
- echo "Building ingress controller VERSION:${VERSION}"
- if [ "${TRAVIS_REPO_SLUG}" == "nginxinc/kubernetes-ingress" ]; then  cd nginx-controller && make clean && 
  make PREFIX=gcr.io/nginx-ic-dev/nginx-ingress VERSION=${VERSION} BUILD_IN_CONTAINER=0 PUSH_TO_GCR=1 ; 
  else echo "Not building PR from forks. Only testing" &&  make test BUILD_IN_CONTAINER=0 ; fi
before_install:
- if [ "${TRAVIS_REPO_SLUG}" == "nginxinc/kubernetes-ingress" ]; then 
  openssl aes-256-cbc -K $encrypted_6e02d569a8a7_key -iv $encrypted_6e02d569a8a7_iv 
  -in client-secret.json.enc -out client-secret.json -d && 
  gcloud auth activate-service-account --key-file client-secret.json &&
  gcloud config set project nginx-ic-dev ; fi 
