language: go

env:
 - GO15VENDOREXPERIMENT=1
go:
 - 1.8.3 
install:
    - export GOPATH="{TRAVIS_BUILD_DIR}/Godeps:${TRAVIS_BUILD_DIR}/nginx-controller:$GOPATH"
script: 
 - go get ./...
 - cd nginx-controller && go test ./...
 - cd nginx-controller && go build -a -installsuffix cgo -ldflags "-w -X main.version=${version}" -o nginx-ingress nginx-controller/*.go
