apiVersion: v1
kind: Secret
metadata:
  name: api-key-client-secret
type: nginx.org/apikey
data:
    client1-premium: cGFzc3dvcmQ= # password
    another-premium: b3BlbnVwcGxlYXNl # openupplease
    client2-basic: YW5vdGhlci1wYXNzd29yZA== # another-password
    client3: bGV0bWVpbg== # letmein
