apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  - name: tea
    service: tea-svc
    port: 80
  policies:
  - name: api-key-policy
  - name: rate-limit-apikey-premium
  - name: rate-limit-apikey-basic
  routes:
  - path: /coffee
    action:
      pass: coffee
  - path: /tea
    action:
      pass: tea
    # policies:
    #   - name: rate-limit-apikey-gold
    #   - name: rate-limit-apikey-silver
    #   - name: rate-limit-apikey-bronze
