apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-gold
spec:
  rateLimit:
    rate: 15r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "~^.*-gold$"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-silver
spec:
  rateLimit:
    rate: 10r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "~^.*-silver$"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-bronze
spec:
  rateLimit:
    rate: 1r/m
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "~^.*-bronze$"
      default: true
---
