apiVersion: v2
name: nginx-ingress
version: 0.16.0
appVersion: 3.0.0
kubeVersion: ">= 1.21.0-0"
type: application
description: NGINX Ingress Controller
icon: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.0.0/deployments/helm-chart/chart-icon.png
home: https://github.com/nginxinc/kubernetes-ingress
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/v3.0.0/deployments/helm-chart
keywords:
  - ingress
  - nginx
maintainers:
  - name: nginxinc
    email: kubernetes@nginx.com
