apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
spec:
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee
