// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned/typed/externaldnsk8s/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeExternaldnsK8sV1alpha1 struct {
	*testing.Fake
}

func (c *FakeExternaldnsK8sV1alpha1) DNSEndpoints(namespace string) v1alpha1.DNSEndpointInterface {
	return newFakeDNSEndpoints(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExternaldnsK8sV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
