// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldnsk8s/v1alpha1"
	externaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/externaldnsk8s/v1alpha1"
	typedexternaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned/typed/externaldnsk8s/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDNSEndpoints implements DNSEndpointInterface
type fakeDNSEndpoints struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.DNSEndpoint, *v1alpha1.DNSEndpointList, *externaldnsk8sv1alpha1.DNSEndpointApplyConfiguration]
	Fake *FakeExternaldnsK8sV1alpha1
}

func newFakeDNSEndpoints(fake *FakeExternaldnsK8sV1alpha1, namespace string) typedexternaldnsk8sv1alpha1.DNSEndpointInterface {
	return &fakeDNSEndpoints{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.DNSEndpoint, *v1alpha1.DNSEndpointList, *externaldnsk8sv1alpha1.DNSEndpointApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("dnsendpoints"),
			v1alpha1.SchemeGroupVersion.WithKind("DNSEndpoint"),
			func() *v1alpha1.DNSEndpoint { return &v1alpha1.DNSEndpoint{} },
			func() *v1alpha1.DNSEndpointList { return &v1alpha1.DNSEndpointList{} },
			func(dst, src *v1alpha1.DNSEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DNSEndpointList) []*v1alpha1.DNSEndpoint {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.DNSEndpointList, items []*v1alpha1.DNSEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
