// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BundleSourceApplyConfiguration represents a declarative configuration of the BundleSource type for use
// with apply.
//
// BundleSource configures fetching a pre-compiled WAF bundle from a remote source.
//
// Three source types are supported:
// - HTTPS (default): fetch a pre-compiled .tgz bundle from any HTTPS server.
// - NIM: pull a named managed policy from NGINX Instance Manager via its API.
// - N1C: pull a named managed policy from NGINX One Console via its API.
//
// Type-specific field requirements (policyName required for NIM/N1C, policyNamespace
// required for N1C) are enforced by the controller's Go validation layer.
type BundleSourceApplyConfiguration struct {
	// Type is the bundle source backend. Defaults to HTTPS.
	Type *configurationv1.BundleSourceType `json:"type,omitempty"`
	// URL is the full bundle URL for HTTPS type, or the API base URL for NIM/N1C. Must use https://.
	URL *string `json:"url,omitempty"`
	// Secret is the name of a Kubernetes Secret in the same namespace as the Policy.
	// For HTTPS: kubernetes.io/tls (tls.crt + tls.key for client mTLS; optional ca.crt for server CA).
	// For N1C/NIM: nginx.com/waf-bundle Secret with a 'token' field containing the management plane API token.
	// For NIM: Opaque Secret with username+password or token field.
	Secret *string `json:"secret,omitempty"`
	// PolicyName is the policy name on the management plane. Required for NIM and N1C; forbidden for HTTPS.
	PolicyName *string `json:"policyName,omitempty"`
	// PolicyNamespace is the namespace/tenant on the management plane. Required for N1C only.
	PolicyNamespace *string `json:"policyNamespace,omitempty"`
	// PollInterval is how often to re-fetch the bundle. Minimum 10s. Default 1m.
	PollInterval *metav1.Duration `json:"pollInterval,omitempty"`
	// Timeout is the per-request HTTP timeout. Default 60s.
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// RetryAttempts is the number of retry attempts on transient failure. Range 1–10.
	RetryAttempts *int `json:"retryAttempts,omitempty"`
	// VerifyChecksum enables SHA-256 verification of the downloaded bundle. HTTPS type only.
	VerifyChecksum *bool `json:"verifyChecksum,omitempty"`
}

// BundleSourceApplyConfiguration constructs a declarative configuration of the BundleSource type for use with
// apply.
func BundleSource() *BundleSourceApplyConfiguration {
	return &BundleSourceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithType(value configurationv1.BundleSourceType) *BundleSourceApplyConfiguration {
	b.Type = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithURL(value string) *BundleSourceApplyConfiguration {
	b.URL = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithSecret(value string) *BundleSourceApplyConfiguration {
	b.Secret = &value
	return b
}

// WithPolicyName sets the PolicyName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyName field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithPolicyName(value string) *BundleSourceApplyConfiguration {
	b.PolicyName = &value
	return b
}

// WithPolicyNamespace sets the PolicyNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyNamespace field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithPolicyNamespace(value string) *BundleSourceApplyConfiguration {
	b.PolicyNamespace = &value
	return b
}

// WithPollInterval sets the PollInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PollInterval field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithPollInterval(value metav1.Duration) *BundleSourceApplyConfiguration {
	b.PollInterval = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithTimeout(value metav1.Duration) *BundleSourceApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithRetryAttempts sets the RetryAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryAttempts field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithRetryAttempts(value int) *BundleSourceApplyConfiguration {
	b.RetryAttempts = &value
	return b
}

// WithVerifyChecksum sets the VerifyChecksum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifyChecksum field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithVerifyChecksum(value bool) *BundleSourceApplyConfiguration {
	b.VerifyChecksum = &value
	return b
}
