// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BundleSourceApplyConfiguration represents a declarative configuration of the BundleSource type for use
// with apply.
//
// BundleSource defines a remote source for fetching AppProtect bundles.
type BundleSourceApplyConfiguration struct {
	// URL is the HTTPS endpoint to fetch the bundle tarball from.
	URL *string `json:"url,omitempty"`
	// TLSSecret is a reference to a kubernetes.io/tls Secret for mTLS authentication.
	// The secret must contain tls.crt and tls.key. An optional ca.crt entry is used
	// to verify the remote server's certificate. It must be in the same namespace as the Policy resource.
	TLSSecret *string `json:"tlsSecret,omitempty"`
	// PollInterval defines how frequently to check for bundle updates via ETag.
	// Default: 1m. Format: Go duration string (e.g., "30s", "2m", "1h").
	PollInterval *string `json:"pollInterval,omitempty"`
}

// BundleSourceApplyConfiguration constructs a declarative configuration of the BundleSource type for use with
// apply.
func BundleSource() *BundleSourceApplyConfiguration {
	return &BundleSourceApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithURL(value string) *BundleSourceApplyConfiguration {
	b.URL = &value
	return b
}

// WithTLSSecret sets the TLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSSecret field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithTLSSecret(value string) *BundleSourceApplyConfiguration {
	b.TLSSecret = &value
	return b
}

// WithPollInterval sets the PollInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PollInterval field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithPollInterval(value string) *BundleSourceApplyConfiguration {
	b.PollInterval = &value
	return b
}
