// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ExternalAuthApplyConfiguration represents a declarative configuration of the ExternalAuth type for use
// with apply.
//
// ExternalAuth defines an external authentication policy for authenticating client requests using an external authentication server, which can be used for example with the oauth2-proxy or any custom authentication server that requires redirection for authentication.
type ExternalAuthApplyConfiguration struct {
	// AuthURL is the URL of the external authentication server to which the request will be sent for authentication. The URL can be an absolute URL, for example http://auth-server/auth, or a relative URL, for example /auth, in which case it will be resolved against the ingress controller's address.
	AuthURL *string `json:"authURL,omitempty"`
	// TODO come back to default value
	// AuthSigninURL is the URL which requests will be redirected to if the external authentication server determines that the client needs to be authenticated. This is typically used when the external authentication server is an oauth2-proxy or any custom authentication server that requires redirection for authentication. The URL can be an absolute URL, for example http://auth-server/signin, or a relative URL, for example /signin, in which case it will be resolved against the ingress controller's address.
	AuthSigninURL *string `json:"authSigninURL,omitempty"`
	// AuthSnippets can be used to add custom configuration snippets to the location block of the external authentication configuration. This can be used for example to add additional headers to the request sent to the external authentication server, or to configure additional parameters for the auth_request module. The content of this field will be added as-is to the location block, so it must be a valid NGINX configuration snippet.
	AuthSnippets *string `json:"authSnippets,omitempty"`
}

// ExternalAuthApplyConfiguration constructs a declarative configuration of the ExternalAuth type for use with
// apply.
func ExternalAuth() *ExternalAuthApplyConfiguration {
	return &ExternalAuthApplyConfiguration{}
}

// WithAuthURL sets the AuthURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthURL field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthURL(value string) *ExternalAuthApplyConfiguration {
	b.AuthURL = &value
	return b
}

// WithAuthSigninURL sets the AuthSigninURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSigninURL field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthSigninURL(value string) *ExternalAuthApplyConfiguration {
	b.AuthSigninURL = &value
	return b
}

// WithAuthSnippets sets the AuthSnippets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSnippets field is set to the value of the last call.
func (b *ExternalAuthApplyConfiguration) WithAuthSnippets(value string) *ExternalAuthApplyConfiguration {
	b.AuthSnippets = &value
	return b
}
