// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HSTSApplyConfiguration represents a declarative configuration of the HSTS type for use
// with apply.
type HSTSApplyConfiguration struct {
	// MaxAge defines how long (in seconds) the browser should cache and enforce the HSTS policy.
	MaxAge *int `json:"maxAge,omitempty"`
	// IncludeSubDomains extends the HSTS policy to all subdomains of the host.
	IncludeSubDomains *bool `json:"includeSubDomains,omitempty"`
	// BehindProxy configures NGINX to set the HSTS header based on the X-Forwarded-Proto request header rather than the $https variable.
	BehindProxy *bool `json:"behindProxy,omitempty"`
}

// HSTSApplyConfiguration constructs a declarative configuration of the HSTS type for use with
// apply.
func HSTS() *HSTSApplyConfiguration {
	return &HSTSApplyConfiguration{}
}

// WithMaxAge sets the MaxAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAge field is set to the value of the last call.
func (b *HSTSApplyConfiguration) WithMaxAge(value int) *HSTSApplyConfiguration {
	b.MaxAge = &value
	return b
}

// WithIncludeSubDomains sets the IncludeSubDomains field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeSubDomains field is set to the value of the last call.
func (b *HSTSApplyConfiguration) WithIncludeSubDomains(value bool) *HSTSApplyConfiguration {
	b.IncludeSubDomains = &value
	return b
}

// WithBehindProxy sets the BehindProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BehindProxy field is set to the value of the last call.
func (b *HSTSApplyConfiguration) WithBehindProxy(value bool) *HSTSApplyConfiguration {
	b.BehindProxy = &value
	return b
}
