// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// OIDCv2ApplyConfiguration represents a declarative configuration of the OIDCv2 type for use
// with apply.
//
// The OIDCv2 policy configures NGINX Plus as a relying party for OpenID Connect authentication using the native ngx_http_oidc_module.
type OIDCv2ApplyConfiguration struct {
	// Sets the Issuer Identifier URL of the OpenID Provider; required directive. The URL must exactly match the value of “issuer” in the OpenID Provider metadata and requires the “https” scheme.
	Issuer *string `json:"issuer,omitempty"`
	// The client ID provided by your OpenID Connect provider.
	ClientID *string `json:"clientID,omitempty"`
	// The name of the Kubernetes secret that stores the client secret provided by your OpenID Connect provider. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/oidc, and the secret under the key client-secret, otherwise the secret will be rejected as invalid. If PKCE is enabled, this should be not configured.
	ClientSecret *string `json:"clientSecret,omitempty"`
	// ConfigURL is the URL of the OpenID Provider Configuration Information. If not set, it will be default to https://<issuer>/.well-known/openid-configuration.
	ConfigURL *string `json:"configURL,omitempty"`
	// List of OpenID Connect scopes. The scope openid always needs to be present and others can be added concatenating them with a + sign, for example openid+profile+email, openid+email+userDefinedScope. The default is openid.
	Scope *string `json:"scope,omitempty"`
	// Allows overriding the default redirect URI. The default is /oidc_callback.
	RedirectURI *string `json:"redirectURI,omitempty"`
	// URL provided by your OpenID Connect provider to request the end user be logged out.
	LogoutURI *string `json:"logoutURI,omitempty"`
	// URI to redirect to after the logout has been performed. Requires endSessionEndpoint.
	PostLogoutRedirectURI *string `json:"postLogoutRedirectURI,omitempty"`
	// Enables downloading of the UserInfo data and makes UserInfo claims available via the $oidc_claim_name variables
	UserInfoEnable *bool `json:"userInfoEnable,omitempty"`
}

// OIDCv2ApplyConfiguration constructs a declarative configuration of the OIDCv2 type for use with
// apply.
func OIDCv2() *OIDCv2ApplyConfiguration {
	return &OIDCv2ApplyConfiguration{}
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithIssuer(value string) *OIDCv2ApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithClientID(value string) *OIDCv2ApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithClientSecret(value string) *OIDCv2ApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithConfigURL sets the ConfigURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigURL field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithConfigURL(value string) *OIDCv2ApplyConfiguration {
	b.ConfigURL = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithScope(value string) *OIDCv2ApplyConfiguration {
	b.Scope = &value
	return b
}

// WithRedirectURI sets the RedirectURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedirectURI field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithRedirectURI(value string) *OIDCv2ApplyConfiguration {
	b.RedirectURI = &value
	return b
}

// WithLogoutURI sets the LogoutURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogoutURI field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithLogoutURI(value string) *OIDCv2ApplyConfiguration {
	b.LogoutURI = &value
	return b
}

// WithPostLogoutRedirectURI sets the PostLogoutRedirectURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostLogoutRedirectURI field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithPostLogoutRedirectURI(value string) *OIDCv2ApplyConfiguration {
	b.PostLogoutRedirectURI = &value
	return b
}

// WithUserInfoEnable sets the UserInfoEnable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserInfoEnable field is set to the value of the last call.
func (b *OIDCv2ApplyConfiguration) WithUserInfoEnable(value bool) *OIDCv2ApplyConfiguration {
	b.UserInfoEnable = &value
	return b
}
