apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-two-policy
spec:
  oidc:
    clientID: fclo-two
    clientSecret: fclo-secret-two
    authEndpoint: https://keycloak.example.com/realms/master/protocol/openid-connect/auth
    tokenEndpoint: http://keycloak.nginx-ingress.svc.cluster.local:8080/realms/master/protocol/openid-connect/token
    jwksURI: http://keycloak.nginx-ingress.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs
    endSessionEndpoint: https://keycloak.example.com/realms/master/protocol/openid-connect/logout
    scope: openid+profile+email
    accessTokenEnable: true
