// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	externaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldnsk8s/v1alpha1"
)

// EndpointApplyConfiguration represents a declarative configuration of the Endpoint type for use
// with apply.
//
// Endpoint describes a DNS Endpoint.
type EndpointApplyConfiguration struct {
	// The hostname for the DNS record.
	DNSName *string `json:"dnsName,omitempty"`
	// The targets the DNS record points to.
	Targets *externaldnsk8sv1alpha1.Targets `json:"targets,omitempty"`
	// RecordType type of record, e.g. CNAME, A, SRV, TXT, MX.
	RecordType *string `json:"recordType,omitempty"`
	// TTL for the record.
	RecordTTL *externaldnsk8sv1alpha1.TTL `json:"recordTTL,omitempty"`
	// Labels stores labels defined for the Endpoint.
	Labels *externaldnsk8sv1alpha1.Labels `json:"labels,omitempty"`
	// ProviderSpecific stores provider specific config.
	ProviderSpecific *externaldnsk8sv1alpha1.ProviderSpecific `json:"providerSpecific,omitempty"`
}

// EndpointApplyConfiguration constructs a declarative configuration of the Endpoint type for use with
// apply.
func Endpoint() *EndpointApplyConfiguration {
	return &EndpointApplyConfiguration{}
}

// WithDNSName sets the DNSName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSName field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithDNSName(value string) *EndpointApplyConfiguration {
	b.DNSName = &value
	return b
}

// WithTargets sets the Targets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Targets field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithTargets(value externaldnsk8sv1alpha1.Targets) *EndpointApplyConfiguration {
	b.Targets = &value
	return b
}

// WithRecordType sets the RecordType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordType field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithRecordType(value string) *EndpointApplyConfiguration {
	b.RecordType = &value
	return b
}

// WithRecordTTL sets the RecordTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordTTL field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithRecordTTL(value externaldnsk8sv1alpha1.TTL) *EndpointApplyConfiguration {
	b.RecordTTL = &value
	return b
}

// WithLabels sets the Labels field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Labels field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithLabels(value externaldnsk8sv1alpha1.Labels) *EndpointApplyConfiguration {
	b.Labels = &value
	return b
}

// WithProviderSpecific sets the ProviderSpecific field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSpecific field is set to the value of the last call.
func (b *EndpointApplyConfiguration) WithProviderSpecific(value externaldnsk8sv1alpha1.ProviderSpecific) *EndpointApplyConfiguration {
	b.ProviderSpecific = &value
	return b
}
