# # every External Authentication option enabled.
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "default/basic-auth-svc"
#     sslEnabled: true
#     sslVerify: true
#     sslVerifyDepth: 2
#     sniName: "basic-auth-svc.default.svc.cluster.local"
#     trustedCertSecret: "external-auth-ca-secret"
#     authSnippets: |
#       # Example snippets
# ---
# # sslEnabled
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "default/basic-auth-svc"
#     sslEnabled: true
# ---
# # secret in different namespace
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "default/basic-auth-svc"
#     sslEnabled: true
#     sslVerify: true
#     sniName: "basic-auth-tls-svc.default"
#     trustedCertSecret: "myns/external-auth-ca-secret"
# ---
# # sslEnabled off
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "default/basic-auth-svc"
#     sslEnabled: false
#     sslVerify: false
#     sslVerifyDepth: 2
#     sniName: "basic-auth-svc.default.svc.cluster.local"
#     authSnippets: |
#       # SSL off
# ---
# # service differnt namespace
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "my-namespace/basic-auth-svc"
# ---
# # service ports http
# apiVersion: k8s.nginx.org/v1
# kind: Policy
# metadata:
#   name: external-auth-basic-policy
# spec:
#   externalAuth:
#     authURI: "/auth"
#     authServiceName: "default/basic-auth-svc"
#     authServicePorts:
#       - 80
---
# service ports https
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: external-auth-basic-policy
spec:
  externalAuth:
    authURI: "/auth"
    authServiceName: "default/basic-auth-svc"
    sslEnabled: true
    authServicePorts:
      - 443
