apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: external-auth-oauth2-policy
spec:
  externalAuth:
    authURI: "/oauth2/auth"
    authServiceName: "default/oauth2-proxy-svc"
    authSigninURI: "/oauth2/signin"
    authSnippets: |
      # this is oauth2 auth snippets
