{
 "title": "NGINX Plus Ingress Controller",
 "description": "A rich collection of Prometheus metrics from NGINX Plus Kubernetes Ingress Controller",
 "tags": [
  "nginx",
  "plus",
  "ingress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "class",
    "label": "Class",
    "query": "label_values(nginx_ingress_nginxplus_up, class)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_ingress_nginxplus_up{class=~\"$class\"}, instance)"
   },
   {
    "name": "server_zone",
    "label": "Server Zone",
    "query": "label_values(nginx_ingress_nginxplus_server_zone_processing{class=~\"$class\"}, server_zone)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(nginx_ingress_nginxplus_upstream_server_state,server)"
   },
   {
    "name": "upstream",
    "label": "Upstream Server",
    "query": "label_values(nginx_ingress_nginxplus_upstream_server_state{class=~\"$class\"}, upstream)"
   }
  ]
 },
 "panels": [
  { "title": "Environment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Plus Reload",
   "type": "stat",
   "description": "Status of the last NGINX Plus reload.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_last_reload_status{class=~\"$class\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Reloads",
   "type": "stat",
   "description": "Number of successful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reloads_total{class=~\"$class\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Reload Errors",
   "type": "stat",
   "description": "Number of unsuccessful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reload_errors_total{class=~\"$class\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Bytes received from clients and sent to clients.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_received{class=~\"$class\", instance=~\"$instance\", server_zone=~\"$server_zone\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_sent{class=~\"$class\", instance=~\"$instance\", server_zone=~\"$server_zone\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Last Reload Time",
   "type": "stat",
   "description": "Last controller reload milliseconds.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_last_reload_milliseconds{class=~\"$class\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Ingress Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Volume",
     "type": "stat",
     "description": "Total http requests per second looking back over the last 5 minutes.",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_nginxplus_http_requests_total{class=~\"$class\", instance=~\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Ingress Count",
     "type": "stat",
     "description": "Total number of deployed Ingress .",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_ingress_resources_total{class=~\"$class\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Zone Request Volume",
     "type": "stat",
     "description": "Total http requests per second looking back over the last 5 minutes across all server zones.",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_requests{class=~\"$class\", instance=~\"$instance\", server_zone=~\"$server_zone\"}[5m]))",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Handled Ingress Resources",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_ingress_resources_total{class=~\"$class\", instance=~\"$instance\", type=\"master\"})",
       "legendFormat": "master"
      },
      {
       "expr": "sum(nginx_ingress_controller_ingress_resources_total{class=~\"$class\", instance=~\"$instance\", type=\"minion\"})",
       "legendFormat": "minion"
      },
      {
       "expr": "sum(nginx_ingress_controller_ingress_resources_total{class=~\"$class\", instance=~\"$instance\", type=\"regular\"})",
       "legendFormat": "regular"
      }
     ]
    },
    {
     "title": "Success Rates Over Time",
     "type": "timeseries",
     "description": " 1|2|3xx response status codes.",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code=\"1xx\", server_zone=~\"$server_zone\"}[5m])) by (ingress)",
       "legendFormat": "Informational"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code=\"2xx\", server_zone=~\"$server_zone\"}[5m]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code=\"3xx\", server_zone=~\"$server_zone\"}[5m]))",
       "legendFormat": "Redirection"
      }
     ]
    },
    {
     "title": "Zone Error Rates Over Time",
     "type": "timeseries",
     "description": " 4|5xx response status codes.",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code=~\"[4].*\", server_zone=~\"$server_zone\"}[2m]))",
       "legendFormat": "Client Errors"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code=~\"[5].*\", server_zone=~\"$server_zone\"}[2m]))",
       "legendFormat": "Server Errors"
      }
     ]
    },
    {
     "title": "Ingress State",
     "type": "stat",
     "description": "Current State of NGINX Ingress Controller.",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nginx_ingress_nginxplus_up{class=~\"$class\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Request Success Rate",
     "type": "stat",
     "description": "Non-4|5xx response status codes divided by total number of response status codes.",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", code!~\"[4-5].*\", server_zone=~\"$server_zone\"}[5m])) / sum(rate(nginx_ingress_nginxplus_server_zone_responses{class=~\"$class\", instance=~\"$instance\", server_zone=~\"$server_zone\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Success Rate",
     "type": "timeseries",
     "description": "Upstream success rate Over Time.",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\", code=\"1xx\"}[5m]))",
       "legendFormat": "Informational"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\", code=\"2xx\"}[5m]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\", code=\"3xx\"}[5m]))",
       "legendFormat": "Redirection"
      }
     ]
    },
    {
     "title": "Upstream Server Count",
     "type": "stat",
     "description": "Total number of upstream servers.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(nginx_ingress_nginxplus_upstream_server_state{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\"})"
      }
     ]
    },
    {
     "title": "Upstream Error Rate",
     "type": "timeseries",
     "description": " 4|5xx Status Codes",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\", code=~\"[4].*\"}[2m]))",
       "legendFormat": "Client Errors"
      },
      {
       "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\", code=~\"[5].*\"}[2m]))",
       "legendFormat": "Server Errors"
      }
     ]
    },
    {
     "title": "Upstream Server State",
     "type": "stat",
     "description": "Current State of the upstream servers.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nginx_ingress_nginxplus_upstream_server_state{class=~\"$class\", instance=~\"$instance\", upstream=~\"$upstream\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSL Performance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes{class=~\"$class\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}} Handshakes"
      },
      {
       "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes_failed{class=~\"$class\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}} Failed"
      },
      {
       "expr": "irate(nginx_ingress_nginxplus_ssl_sessions_reuses{class=~\"$class\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}} Reuses"
      }
     ]
    }
   ]
  }
 ]
}