 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: tcp-echo-server
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: tcp-echo-server
   template:
     metadata:
       labels:
         app: tcp-echo-server
     spec:
       containers:
       - name: tcp-echo-server
         image: alpine
         command: ["/bin/sh"]
         args:
         - -c
         - |
           apk add --no-cache socat
           echo "TCP Echo Server starting..."
           socat -v tcp-listen:7000,fork,reuseaddr,keepalive exec:'/bin/cat'
         ports:
         - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-service
spec:
  selector:
    app: tcp-echo-server
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP
