apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  upstreams:
  - name: secure-app
    service: secure-app
    port: 8443
  routes:
  - path: /
    policies:
        - name: egress-mtls-policy
    action:
      pass: secure-app
