apiVersion: k8s.nginx.org/v1
kind: TransportServer
metadata:
  name: tcp-dns
spec:
  listener:
    name: tcp-ip-dns-listener
    protocol: TCP
  upstreams:
  - name: dns-app
    service: coredns
    port: 5353
  action:
    pass: dns-app
