controller:
  ## Deploys the Ingress Controller for NGINX Plus.
  nginxplus: true
  mgmt:
    ## Secret name of license token for NGINX Plus
    licenseTokenSecretName: "license-token" # required for NGINX Plus
  ## Support for App Protect WAF
  appprotect:
    ## Enable the App Protect WAF module in the Ingress Controller.
    enable: true
    ## Enables App Protect WAF v5.
    v5: true
    ## Sets log level for App Protect WAF. Allowed values: fatal, error, warn, info, debug, trace
    # logLevel: fatal

    # Volumes for App Protect WAF v5
    # Required volumes are: app-protect-bd-config, app-protect-config, and app-protect-bundles
    volumes:
      - name: app-protect-bd-config
        emptyDir: {}
      - name: app-protect-config
        emptyDir: {}
      - name: app-protect-bundles
        persistentVolumeClaim:
          claimName: task-pv-claim

    ## Configuration for App Protect WAF v5 Enforcer
    enforcer:
      host: "127.0.0.1"
      port: 50000
      image:
        repository: gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nap/waf-enforcer
        tag: "5.12.1"
        pullPolicy: Always
      securityContext: {}

    ## Configuration for App Protect WAF v5 Configuration Manager
    configManager:
      image:
        repository: gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nap/waf-config-mgr
        tag: "5.12.1"
        pullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 101 #nginx
        runAsNonRoot: true
        capabilities:
          drop:
            - all
  ## The hostPort configuration for the Ingress Controller pods.
  hostPort:
    ## Enables hostPort for the Ingress Controller pods.
    enable: false

    ## The HTTP hostPort configuration for the Ingress Controller pods.
    http: 80

     ## The HTTPS hostPort configuration for the Ingress Controller pods.
    https: 443
#  ## A list of custom ports to expose on the NGINX Ingress Controller pod. Follows the conventional Kubernetes yaml syntax for container ports.
#  customPorts:
#    - name: tcp-port
#      containerPort: 7000
#      protocol: TCP
  ## The log level of the Ingress Controller. Options include: trace, debug, info, warning, error, fatal
  logLevel: debug
  ## Sets the log format of Ingress Controller. Options include: glog, json, text
  logFormat: glog
  ## Disable IPV6 listeners explicitly for nodes that do not support the IPV6 stack.
  disableIPV6: false
  image:
    ## The image repository of the Ingress Controller.
    repository: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic-nap-v5/nginx-plus-ingress"
#   repository: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic-dos-nap/nginx-plus-ingress:"
    tag: "agent-v2-waf-v5"
#    tag: "5.3.1"
    pullPolicy: Always
#  globalConfiguration:
#    ## Creates the GlobalConfiguration custom resource. Requires controller.enableCustomResources.
#    create: true
#    ## The spec of the GlobalConfiguration for defining the global configuration parameters of the Ingress Controller.
#    spec:
#      listeners:
#        - name: tcp-listener
#          port: 7000
#          protocol: TCP
#  service:
#    ## A list of custom ports to expose through the Ingress Controller service. Follows the conventional Kubernetes yaml syntax for service ports.
#    customPorts:
#      - name: tcp-port
#        port: 7000
#        protocol: TCP
#        targetPort: 7000

  # serviceAccount:
  #   imagePullSecretName: regcred

  volumeMounts:
    - name: app-protect-bundles
      mountPath: /etc/app_protect/bundles/

  enableSnippets: false

  config:
    ## The name of the ConfigMap used by the Ingress Controller.
    ## Autogenerated if not set or set to "".
    # name: nginx-config
    ## The annotations of the Ingress Controller configmap.
    annotations: {}
    ## The entries of the ConfigMap for customizing NGINX configuration.
    entries: {}
  telemetryReporting:
    enable: false
nginxAgent:
  ## Enables NGINX Agent.
  enable: true
  logLevel: "debug"

  # Agent V3 configuration
  # Dataplane key is required to authenticate NGINX Agent with NGINX One Console
  dataplaneKeySecretName: "dataplane-key"
  endpointHost: "agent.connect.nginxlab.net"
  endpointPort: 443
  tlsSkipVerify: false

  # Agent V2 configuration
  ## If nginxAgent.instanceGroup is not set the value of nginx-ingress.controller.fullname will be used
  instanceGroup: ""
  instanceManager:
    # FQDN or IP for connecting to NGINX Instance Manager, e.g. nim.example.com
    host: ""
    grpcPort: 443
    tls:
      enabled: true
      skipVerify: false
      ## kubernetes.io/tls secret with a TLS certificate and key for using mTLS between NGINX Agent and Instance Manager
      secret: ""
      ## nginx.org/ca secret for verification of Instance Manager TLS
      caSecret: ""
    sni: ""
  ## Syslog listener which NGINX Agent uses to accept messages from App Protect WAF
  syslog:
    host: "127.0.0.1"
    port: 1514
  napMonitoring:
    collectorBufferSize: 50000
    processorBufferSize: 50000
  ## The name of a custom ConfigMap to use instead of the one provided by default
  customConfigMap: ""
