apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe2-ingress-coffee-minion
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/proxy-set-headers: "X-Forwarded-Coffee: mocha"
spec:
  ingressClassName: nginx
  rules:
  - host: cafe2.example.com
    http:
      paths:
      - path: /coffee2
        pathType: Prefix
        backend:
          service:
            name: coffee2-svc
            port:
              number: 80
