{{- if .Values.controller.appprotectdos.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-ingress.appProtectDosArbName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginx-ingress.appProtectDosArbName" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-ingress.appProtectDosArbName" . }}
    spec:
      containers:
        - name: {{ include "nginx-ingress.appProtectDosArbName" . }}
          image: "{{ .Values.controller.appprotectdos.arbitrator.repository }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-appprotect-dos-arb
  namespace:  {{ .Release.Namespace }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "nginx-ingress.appProtectDosArbName" . }}
  ports:
    - name: arb
      port: 3000
      protocol: TCP
      targetPort: 3000
  clusterIP: None
{{- end }}
