{{ if and (not .Values.controller.wildcardTLS.secret) (and .Values.controller.wildcardTLS.cert .Values.controller.wildcardTLS.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-tls-secret
  labels:
    app: {{ .Values.controller.name | trunc 63 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.wildcardTLS.cert }}
  tls.key: {{ .Values.controller.wildcardTLS.key }}
{{- end }}