apiVersion: v1
kind: Service
metadata:
  name: {{ default "svc-appprotect-dos-arb" .Values.arbitrator.serviceName }}
  namespace:  {{ .Release.Namespace }}
  labels: {{- include "arbitrator.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "arbitrator.name" . }}
  ports:
    - name: arb
      port: 3000
      protocol: TCP
      targetPort: 3000
  clusterIP: None
