# Save as waf-remote-bundle-policy.yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-remote-bundle-2
  namespace: default
spec:
  waf:
    enable: true
    apBundleSource:
      url: "https://bundle-server.bundle-server.svc.cluster.local/bundles/compiled_policy_2.tgz"
      tlsSecret: "bundle-client-tls"
      pollInterval: "1m"
