.PHONY: run
run: ## Create just in time TLS certificates needed for tests and examples
	go run ./...

.PHONY: clean
clean: ## Clean just in time TLS certificates needed for tests and examples
	go run ./... -clean
