apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment.yaml
- service.yaml
# - ../../crd/bases/appprotectdos.f5.com_apdoslogconfs.yaml
# - ../../crd/bases/appprotectdos.f5.com_apdospolicy.yaml
# - ../../crd/bases/appprotectdos.f5.com_dosprotectedresources.yaml
