package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// renderIndexMarkdown is the always-loaded entry point for agents. Keep it
// short (target ≤120 lines) — it's the most expensive surface in tokens.
func renderIndexMarkdown(
	gi *GoIndex,
	dm *DomainMap,
	tmpls *TemplateIndex,
	helm *HelmIndex,
	pt *PythonTestIndex,
	ex *ExamplesIndex,
) []byte {
	var buf bytes.Buffer
	buf.WriteString("# .codegraph — NIC Code Index\n\n")
	buf.WriteString("Auto-generated by `make codegraph`. Read this file first for *where* things live. For *why/how* (architecture, layers, pipeline), load the `nic-structure` skill.\n\n")

	// Stats line.
	fmt.Fprintf(&buf, "**Coverage**: %d Go packages · %d symbols · %d ref edges · %d templates · %d helm value keys · %d python test files · %d examples\n\n",
		len(gi.Packages), len(gi.Symbols), edgeCount(gi.Refs), len(tmpls.Files), len(helm.ValuesKeys), len(pt.Files), len(ex.Entries))

	// Artifact table.
	buf.WriteString("## Artifacts\n\n")
	buf.WriteString("| File | Purpose |\n| --- | --- |\n")
	rows := [][2]string{
		{"packages.json", "Go package meta + in-repo imports"},
		{"symbols.jsonl", "One symbol per line: kind, name, pkg, file, line, recv, signature"},
		{"refs.jsonl", "Callee → callers (intra-repo, capped at " + itoa(MaxCallersPerSymbol) + ")"},
		{"imports.json", "Go package import graph (in-repo only)"},
		{"files.md", "Per-package file index with top-level exported symbols"},
		{"domain-map.md", "CRD → validators → configs → templates → tests (per CRD)"},
		{"domain-map.json", "Machine-readable version of domain-map.md"},
		{"templates.json", "NGINX `.tmpl` defines/includes; OSS+Plus paired by basename"},
		{"helm.json", "Helm values keys ↔ template usage"},
		{"python-tests.json", "pytest files: classes, tests, markers, fixtures"},
		{"examples.json", "examples/** kind + name + group"},
	}
	for _, r := range rows {
		fmt.Fprintf(&buf, "| `%s` | %s |\n", r[0], r[1])
	}
	buf.WriteString("\n")

	// Query cookbook.
	buf.WriteString("## Query Cookbook\n\n")
	buf.WriteString("All examples assume `cwd` is the repo root. Replace `<X>` with your query string.\n\n")
	buf.WriteString("```bash\n")
	buf.WriteString("# Find a Go symbol by name (file:line):\n")
	buf.WriteString("rg '\"name\":\"<Name>\"' .codegraph/symbols.jsonl\n\n")
	buf.WriteString("# Find every caller of an exported func or method:\n")
	buf.WriteString("rg '\"to\":\"<pkg/path>.<Name>\"' .codegraph/refs.jsonl                # func\n")
	buf.WriteString("rg '\"to\":\"<pkg/path>.<Recv>.<Method>\"' .codegraph/refs.jsonl       # method\n\n")
	buf.WriteString("# Look up a CRD's wiring (validator, config struct, template, tests):\n")
	buf.WriteString("rg -A 12 '## <CRDName>' .codegraph/domain-map.md\n\n")
	buf.WriteString("# Find NGINX templates defining or including a named block:\n")
	buf.WriteString("rg '\"<block-name>\"' .codegraph/templates.json\n\n")
	buf.WriteString("# Find where a Helm value is referenced:\n")
	buf.WriteString("rg -F '\"<dotted.values.key>\"' .codegraph/helm.json\n\n")
	buf.WriteString("# Find Python tests using a fixture or marker:\n")
	buf.WriteString("rg -F '\"<fixture-or-marker>\"' .codegraph/python-tests.json\n\n")
	buf.WriteString("# Find an example manifest by Kubernetes kind:\n")
	buf.WriteString("rg -F '\"kind\":\"<Kind>\"' .codegraph/examples.json\n\n")
	buf.WriteString("# Discover a package's files and exports:\n")
	buf.WriteString("rg -A 50 '^## <import-path>$' .codegraph/files.md\n")
	buf.WriteString("```\n\n")

	// CRD inventory.
	buf.WriteString("## CRDs indexed\n\n")
	for _, e := range dm.Entries {
		group := e.Group
		if group == "" {
			group = "?"
		}
		fmt.Fprintf(&buf, "- `%s` (`%s`) — %d validators, %d configs, %d templates, %d tests\n",
			e.CRD, group, len(e.Validators), len(e.Configs), len(e.Templates), len(e.Tests))
	}
	buf.WriteString("\n")

	// Top packages by symbol count.
	buf.WriteString("## Top packages by symbol count\n\n")
	pkgCounts := map[string]int{}
	for _, s := range gi.Symbols {
		pkgCounts[s.Pkg]++
	}
	type pc struct {
		Pkg string
		N   int
	}
	var pcs []pc
	for p, n := range pkgCounts {
		pcs = append(pcs, pc{p, n})
	}
	sort.Slice(pcs, func(i, j int) bool {
		if pcs[i].N != pcs[j].N {
			return pcs[i].N > pcs[j].N
		}
		return pcs[i].Pkg < pcs[j].Pkg
	})
	limit := 10
	if len(pcs) < limit {
		limit = len(pcs)
	}
	for _, p := range pcs[:limit] {
		fmt.Fprintf(&buf, "- `%s` — %d symbols\n", short(p.Pkg), p.N)
	}
	buf.WriteString("\n")

	// Footer guidance.
	buf.WriteString("## Notes\n\n")
	buf.WriteString("- `refs.jsonl` only contains intra-repo edges. Cross-module calls (`k8s.io/...`, `nginx-plus-go-client`) are deliberately omitted.\n")
	buf.WriteString("- `pkg/client/**`, `**/zz_generated*.go`, `**/fake/**`, and `**/__snapshots__/**` are excluded from the Go index by design.\n")
	buf.WriteString("- `domain-map.md` is heuristic (name match). Use `hack/codegraph/overrides.yaml` to patch gaps when adding a CRD field.\n")
	buf.WriteString("- Regenerate with `make codegraph`. CI runs `make codegraph-check` and fails PRs with stale indexes.\n")
	return buf.Bytes()
}

func edgeCount(refs map[string][]RefInfo) int {
	n := 0
	for _, r := range refs {
		n += len(r)
	}
	return n
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

// _ ensures strings import stays even if future edits drop usage.
var _ = strings.HasPrefix
