apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: default
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          args:
            - --provider=oidc
            - --oidc-issuer-url=https://keycloak.default.svc.cluster.local:8443
            - --client-id=oauth2-proxy-client
            - --client-secret-file=/etc/secrets/client-secret
            - --cookie-secure=false
            - --redirect-url=http://localhost:4180/oauth2/callback
            - --http-address=0.0.0.0:4180
            - --upstream=http://127.0.0.1/
            - --set-xauthrequest=true
            - --email-domain=*
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-cookie-secret
                  key: cookie-secret
          volumeMounts:
            - name: client-secret
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: client-secret
          secret:
            secretName: oauth2-proxy-client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: default
  labels:
    app: oauth2-proxy
spec:
  ports:
    - port: 4180
      targetPort: 4180
  selector:
    app: oauth2-proxy

# Note: This manifest no longer creates the oauth2 secrets. Create the following secrets BEFORE applying this manifest:
#  - oauth2-proxy-client-secret (type: nginx.org/oidc) containing key 'client-secret'
#  - oauth2-proxy-cookie-secret (opaque) containing key 'cookie-secret' with a base64 32-byte value
# See README for exact commands.
