apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: jwt-policy
spec:
  jwt:
    realm: MyProductAPI
    token: $http_token
#    jwksURI: http://10.42.0.67:8080/realms/example/protocol/openid-connect/certs

    jwksURI: http://keycloak.default.svc.cluster.local:8080/realms/example/protocol/openid-connect/certs
#    keyCache: 10m

