kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  otel-exporter-endpoint: "otel.example.com:4317"
  otel-service-name: "nginx-ingress-controller:nginx"
  otel-exporter-header-name: "x-otel-header"
  otel-exporter-header-value: "otel-header-value"
  # otel-trace-in-http: "true" # Uncomment to enable tracing at the HTTP level
