// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	externaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldnsk8s/v1alpha1"
	applyconfigurationexternaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/externaldnsk8s/v1alpha1"
	scheme "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DNSEndpointsGetter has a method to return a DNSEndpointInterface.
// A group's client should implement this interface.
type DNSEndpointsGetter interface {
	DNSEndpoints(namespace string) DNSEndpointInterface
}

// DNSEndpointInterface has methods to work with DNSEndpoint resources.
type DNSEndpointInterface interface {
	Create(ctx context.Context, dNSEndpoint *externaldnsk8sv1alpha1.DNSEndpoint, opts v1.CreateOptions) (*externaldnsk8sv1alpha1.DNSEndpoint, error)
	Update(ctx context.Context, dNSEndpoint *externaldnsk8sv1alpha1.DNSEndpoint, opts v1.UpdateOptions) (*externaldnsk8sv1alpha1.DNSEndpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dNSEndpoint *externaldnsk8sv1alpha1.DNSEndpoint, opts v1.UpdateOptions) (*externaldnsk8sv1alpha1.DNSEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*externaldnsk8sv1alpha1.DNSEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*externaldnsk8sv1alpha1.DNSEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *externaldnsk8sv1alpha1.DNSEndpoint, err error)
	Apply(ctx context.Context, dNSEndpoint *applyconfigurationexternaldnsk8sv1alpha1.DNSEndpointApplyConfiguration, opts v1.ApplyOptions) (result *externaldnsk8sv1alpha1.DNSEndpoint, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, dNSEndpoint *applyconfigurationexternaldnsk8sv1alpha1.DNSEndpointApplyConfiguration, opts v1.ApplyOptions) (result *externaldnsk8sv1alpha1.DNSEndpoint, err error)
	DNSEndpointExpansion
}

// dNSEndpoints implements DNSEndpointInterface
type dNSEndpoints struct {
	*gentype.ClientWithListAndApply[*externaldnsk8sv1alpha1.DNSEndpoint, *externaldnsk8sv1alpha1.DNSEndpointList, *applyconfigurationexternaldnsk8sv1alpha1.DNSEndpointApplyConfiguration]
}

// newDNSEndpoints returns a DNSEndpoints
func newDNSEndpoints(c *ExternaldnsK8sV1alpha1Client, namespace string) *dNSEndpoints {
	return &dNSEndpoints{
		gentype.NewClientWithListAndApply[*externaldnsk8sv1alpha1.DNSEndpoint, *externaldnsk8sv1alpha1.DNSEndpointList, *applyconfigurationexternaldnsk8sv1alpha1.DNSEndpointApplyConfiguration](
			"dnsendpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *externaldnsk8sv1alpha1.DNSEndpoint { return &externaldnsk8sv1alpha1.DNSEndpoint{} },
			func() *externaldnsk8sv1alpha1.DNSEndpointList { return &externaldnsk8sv1alpha1.DNSEndpointList{} },
		),
	}
}
