// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	externaldnsk8sv1alpha1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldnsk8s/v1alpha1"
	scheme "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ExternaldnsK8sV1alpha1Interface interface {
	RESTClient() rest.Interface
	DNSEndpointsGetter
}

// ExternaldnsK8sV1alpha1Client is used to interact with features provided by the externaldns.k8s.io group.
type ExternaldnsK8sV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ExternaldnsK8sV1alpha1Client) DNSEndpoints(namespace string) DNSEndpointInterface {
	return newDNSEndpoints(c, namespace)
}

// NewForConfig creates a new ExternaldnsK8sV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ExternaldnsK8sV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ExternaldnsK8sV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ExternaldnsK8sV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ExternaldnsK8sV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ExternaldnsK8sV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ExternaldnsK8sV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ExternaldnsK8sV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ExternaldnsK8sV1alpha1Client {
	return &ExternaldnsK8sV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := externaldnsk8sv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ExternaldnsK8sV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
