apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  policies:
    - name: cors-policy
  upstreams:
    - name: webapp
      service: webapp-svc
      port: 80
  routes:
    - path: /
      action:
        pass: webapp
    - path: /api
      policies:
        - name: cors-wildcard-policy  # Different CORS policy for API routes
      action:
        pass: webapp
