apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: wildcard-cors-policy
  namespace: default
spec:
  cors:
    # Wildcard subdomain support - allows any single-level subdomain
    allowOrigin:
      - "https://*.example.com"
      - "https://test.example.com"
    allowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "OPTIONS"
    allowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    allowCredentials: true
    exposeHeaders:
      - "X-Total-Count"
      - "X-Page-Size"
    maxAge: 86400
