apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-premium
spec:
  rateLimit:
    rate: 100r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        clients:
          - "client-1"
          - "client-2"
          - "client-3"
          - "~^.*-premium$"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-basic
spec:
  rateLimit:
    rate: 10r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        clients:
          - "client-4"
          - "client-5"
          - "client-6"
          - "~^.*-basic$"
      default: true
---
