name: Certify UBI image
run-name: Certify UBI image ${{ inputs.image }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to certify"
        required: true
        type: string
      submit:
        description: "Submit results to Redhat"
        required: false
        type: boolean
        default: false
      preflight_version:
        description: "Preflight version to use"
        required: false
        type: string
        default: "1.11.1"
  push:
    branches:
      - certify-updates

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  certify-ubi-images:
    name: Certify OpenShift UBI images
    runs-on: ubuntu-24.04
    steps:
      - name: Certify UBI OSS images in quay
        uses: ./.github/actions/certify-openshift-image
        with:
          image: ${{ inputs.image || 'quay.io/nginx/nginx-ingress:3.6.0-ubi' }}
          project_id: ${{ secrets.CERTIFICATION_PROJECT_ID }}
          pyxis_token: ${{ secrets.PYXIS_API_TOKEN }}
          preflight_version: ${{ inputs.preflight_version || '1.11.1' }}
          submit: ${{ inputs.submit || false }}
