name: "Cherry-pick dependencies to release branch"
on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick_to_release:
    runs-on: ubuntu-latest
    name: Cherry pick into release-3.5
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0
      - name: Cherry pick into release-3.5
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.10
        with:
          branch: release-3.5
          author: nginx-bot <integrations@nginx.com>
          labels: |
            dependencies
          reviewers: |
            kic
