name: "Cherry-pick dependencies to release branch"
on:
  pull_request:
    branches:
      - main
    types: ["closed"]

permissions:
  contents: read

jobs:
  cherry_pick_to_release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    name: Cherry pick into release-3.5
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c1
        with:
          fetch-depth: 0
      - name: Cherry pick into release-3.5
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-3.5
          author: nginx-bot <integrations@nginx.com>
          labels: |
            dependencies
          reviewers: |
            kic
