name: "Create Tag on release branch"

on:
  workflow_dispatch:
    inputs:
      release_branch:
        required: true
        type: string
        default: 'release-0.0'
      tag:
        required: false
        type: string
        default: 'vx.x.x'
      dry_run:
        type: boolean
        default: false


defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  create:
    name: Create Tag on release branch in NIC repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout NIC repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: ${{ inputs.release_branch }}

      - name: Create new release Tag
        run: |
          branch="${{ inputs.release_branch }}"
          tag="${{ inputs.tag }}"
          if git rev-parse --verify refs/tags/${tag}; then
            echo "Adding tag ${tag}."
            git tag -a ${tag} -m "Version ${tag#v*}"
            echo "Pushing to tag ${tag} to branch ${branch}"
            if ! ${{ inputs.dry_run }}; then
                git push origin "${tag}"
            else
                echo "DRY RUN not making any changes"
                git push --dry-run origin "${tag}"
            fi
          else
            echo "Warning: Tag ${tag} already exists.  Not making any changes"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.NGINX_PAT }}
