name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

concurrency:
  group: ${{ github.ref_name }}-dockerhub
  cancel-in-progress: true


jobs:
  dockerHubDescription:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Modify readme for DockerHub
        run: |
          sed -i '3,4d' README.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@579f64ca0abced29dbbc44ab4c6a0b9e33ab3588 # v3.4.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nginx/nginx-ingress
          short-description: ${{ github.event.repository.description }}
