name: Build and deploy docs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - dev
          - staging
          - prod
  pull_request:
    branches:
      - "*"
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  call-docs-build-push:
    uses: nginxinc/docs-actions/.github/workflows/docs-build-push.yml@69843fb5d009e99750e50c23e90c23a899e4637e # v1.0.6
    permissions:
      pull-requests: write # needed to write preview url comment to PR
      contents: read
    with:
      production_url_path: "/nginx-ingress-controller"
      preview_url_path: "/previews/nginx-ingress-controller"
      docs_source_path: "public/nginx-ingress-controller"
      docs_build_path: "./docs"
      doc_type: "hugo"
      environment: ${{ inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DOCS }}
      AZURE_KEY_VAULT: ${{ secrets.AZURE_KEY_VAULT_DOCS }}
