name: Build and deploy docs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - dev
          - staging
          - prod
      hugo_theme_override:
        description: 'Override hugo theme (leave blank to use latest version)'
        required: false
        default: ''
        type: string
  pull_request:
    branches:
      - "*"
    paths:
      - "site/**"
  push:
    branches:
      - "release-3.7"

permissions:
  contents: read

jobs:
  call-docs-build-push:
    uses: nginxinc/docs-actions/.github/workflows/docs-build-push.yml@9c59fab05a8131f4d691ba6ea2b6a119f3ef832a # v1.0.7
    permissions:
      pull-requests: write # needed to write preview url comment to PR
      contents: read
    with:
      production_url_path: "/nginx-ingress-controller"
      preview_url_path: "/previews/nginx-ingress-controller"
      docs_source_path: "public/nginx-ingress-controller"
      docs_build_path: "./site"
      doc_type: "hugo"
      environment: ${{ inputs.environment }}
      force_hugo_theme_version: ${{inputs.hugo_theme_override}}
      auto_deploy_branch: "release-3.7"
      auto_deploy_env: "prod"
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DOCS }}
      AZURE_KEY_VAULT: ${{ secrets.AZURE_KEY_VAULT_DOCS }}
