name: Mend

on:
  push:
    branches:
      - main
    paths-ignore:
      - site/**
      - examples/**
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false
        default: main
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Mend
    if: ${{ github.event.repository.fork == false }}
    uses: nginxinc/compliance-rules/.github/workflows/mend.yml@c903bfe6c668eaba362cde6a7882278bc1564401 # v0.1
    secrets: inherit
    with:
      product_name: kubernetes-ingress-controller_${{ inputs.branch && inputs.branch || github.ref_name }}
      project_name: nic
