name: "Test staging repository for Plus release LTS"

on:
  push:
    branches:
      - chore/split-release-creation-and-publishing

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release-to-nginx-registry:
    name: Push Plus images to the NGINX Registry
    runs-on: 'kic-plus'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Id Token
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: idtoken
        with:
          script: |
            let id_token = await core.getIDToken()
            core.setOutput('id_token', id_token)

      - name: Login to Test Management Registry
        id: docker-mgmt-test-auth
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: docker-mgmt-test.nginx.com
          username: ${{ steps.idtoken.outputs.id_token }}
          password: ${{ github.actor }}

      - name: Login to NGINX Registry
        id: docker-mgmt-auth
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: docker-mgmt.nginx.com
          username: ${{ steps.idtoken.outputs.id_token }}
          password: ${{ github.actor }}

      - name: Publish images
        run: |
          cat ~/.docker/config.json
          export CONFIG_PATH=.github/config/config-plus-nginx-lts-test
          export SOURCE_REGISTRY=docker-mgmt.nginx.com
          export SOURCE_TAG=5.5.4
          export TARGET_TAG=5.5.4
          .github/scripts/copy-images.sh
