name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

env:
  DOCKER_BUILDKIT: 1
  HELM_CHART_DIR: deployments/helm-chart
  GIT_NAME: NGINX Kubernetes Team
  GIT_MAIL: kubernetes@nginx.com

jobs:

  binary:
    name: Build Binary
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.commit.outputs.version }}
      helmChartVersion: ${{ steps.commit.outputs.helmChartVersion }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Output Variables
        id: commit
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
          echo "::set-output name=helmChartVersion::$(helm show chart ${{ env.HELM_CHART_DIR }} | grep 'version:' | cut -d ' ' -f 2)"
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Determine GOPATH
        run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
      - run: npm install js-yaml
        continue-on-error: true
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish release on tag
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const ref = context.ref.split("/")[2]
              const yaml = require('js-yaml');
              const releases = (await github.rest.repos.listReleases({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                per_page: 100,
              })).data
              const draft_release = releases.find(release => release.draft && release.tag_name === ref)
              const helm_file = (await github.rest.repos.getContent({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                path: "deployments/helm-chart/Chart.yaml",
                ref: ref,
              })).data.content
              const helm_yaml = yaml.load(Buffer.from(helm_file, 'base64').toString())
              const helm_version = helm_yaml.version
              console.log(`Helm version: ${helm_version}`)
              const update = await github.rest.repos.updateRelease({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                release_id: draft_release.id,
                body: draft_release.body.replace("%HELM_CHART_VERSION%", helm_version),
                draft: false
              });
              console.log(`Release published: ${update.data.html_url}`)
              console.log(`Release notes: ${update.data.body}`)

      - name: Download Syft
        uses: anchore/sbom-action/download-syft@v0.12.0

      - name: Build binaries
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: ${{ env.GOPATH }}
      - name: Store Artifacts in Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}

  release-docker:
    name: Release Images
    runs-on: ubuntu-20.04
    needs: [binary]
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: ${{ needs.binary.outputs.version }}
            type: debian
            platforms: linux/arm,linux/arm64,linux/amd64,linux/ppc64le,linux/s390x
          - tag: ${{ needs.binary.outputs.version }}-alpine
            type: alpine
            platforms: linux/arm,linux/arm64,linux/amd64,linux/ppc64le,linux/s390x
          - tag: ${{ needs.binary.outputs.version }}-ubi
            type: ubi
            platforms: linux/arm64,linux/amd64,linux/s390x
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Output Variables
        id: commit
        run: |
          echo "::set-output name=date::$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "::set-output name=nginx_version::$(cat build/Dockerfile | grep -m1 "FROM nginx:" | cut -d":" -f2 | cut -d" " -f1)"
      - name: Fetch Cached Artifacts
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64,ppc64le,s390x
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          file: build/Dockerfile
          context: '.'
          no-cache: true
          cache-to: type=gha,scope=${{ matrix.type }},mode=max
          target: goreleaser
          tags: nginx/nginx-ingress:${{ matrix.tag }}
          platforms: ${{ matrix.platforms }}
          push: true
          pull: true
          build-args: |
            BUILD_OS=${{ matrix.type }}
            IC_VERSION=v${{ needs.binary.outputs.version }}
            NGINX_VERSION=${{ steps.commit.outputs.nginx_version }}
            DATE=${{ steps.commit.outputs.date }}
            GIT_COMMIT=${{ github.sha }}

  package-helm:
    name: Package Helm Chart
    runs-on: ubuntu-20.04
    needs: [binary, release-docker]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Lint
        run: helm lint ${{ env.HELM_CHART_DIR }}
      - name: Package
        run: helm package --version ${{ needs.binary.outputs.helmChartVersion }} ${{ env.HELM_CHART_DIR }}
      - name: Upload Chart
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: ${{ github.workspace }}/nginx-ingress-${{ needs.binary.outputs.helmChartVersion }}.tgz

  release-helm:
    name: Release Helm Chart
    runs-on: ubuntu-20.04
    needs: [binary, release-docker, package-helm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: nginxinc/helm-charts
          fetch-depth: 1
          token: ${{ secrets.NGINX_PAT }}
      - name: Remove previous Chart
        run: rm -f ${{ github.workspace }}/stable/nginx-ingress-${{ needs.binary.outputs.helmChartVersion }}.tgz
      - name: Retrieve latest Helm Chart
        uses: actions/download-artifact@v3
        with:
          name: helm-chart
          path: ${{ github.workspace }}/stable
      - name: Push Helm Chart
        run: |
          helm repo index stable --url https://helm.nginx.com/stable
          git add -A
          git -c user.name='${{ env.GIT_NAME }}' -c user.email='${{ env.GIT_MAIL }}' \
          commit -m "NGINX Ingress Controller - Release ${{ needs.binary.outputs.version }}"
          git push -u origin master

  notify:
    name: Notify
    runs-on: ubuntu-20.04
    needs: publish-release-notes
    if: always()
    steps:
      - name: Workflow Status
        id: check
        uses: martialonline/workflow-status@v2
      - name: Output Variables
        id: commit
        run: |
          echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"
          echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)"
      - name: Send Notification
        uses: 8398a7/action-slack@v3
        if:
          steps.check.outputs.status == 'failure' ||
          steps.check.outputs.status == 'cancelled'
        with:
          status: custom
          custom_payload: |
            {
              username: 'Github',
              icon_emoji: ':octocat:',
              mention: 'channel',
              attachments: [{
                title: '[${{ needs.binary.outputs.repo }}] ${{ github.workflow }} pipeline has failed',
                color: '${{ steps.check.outputs.status }}' == 'failure' ? 'danger' : 'warning',
                fields: [{
                  title: 'Commit Hash',
                  value: '${{ needs.binary.outputs.sha }}',
                  short: true
                },
                {
                  title: 'Author',
                  value: '${{ github.actor }}',
                  short: true
                },
                {
                  title: 'Pipeline URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
