name: Release NIC

on:
  push:
    branches:
      - chore/nginx-pat

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  # Disable GCP Marketplace step for now until a decision is made on how to handle GCP Marketplace with licensing
  gcp-marketplace:
    name: Trigger PR for GCP Marketplace
    runs-on: ubuntu-24.04
    steps:
      - name:
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.NGINX_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'kubernetes-ingress-gcp',
              workflow_id: 'sync-chart.yml',
              ref: 'main',
              inputs: {
                chart_version: '3.3.0'
              },
            })
