name: Release Drafter

on:
  push:
    branches:
      - release-2.1

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
