name: Release NIC
run-name: ${{ inputs.dry_run && '[DRY RUN] ' || '' }}Release NIC ${{ inputs.nic_version }} from ${{ inputs.release_branch }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      nic_version:
        description: "Version to release"
        required: true
        type: string
      source_tag:
        description: "Source tag to release"
        required: false
        type: string
      chart_version:
        description: "Helm Chart version to release"
        required: false
        type: string
      cnab_version:
        description: "CNAB version for Azure Marketplace"
        required: false
        type: string
      operator_version:
        description: "Operator version to set"
        required: false
        type: string
      release_branch:
        description: "Branch to release from"
        required: true
        type: string
      dry_run:
        description: "Dry Run?"
        type: boolean
        default: false
      skip_step:
        description: "Comma separated list of jobs to skip"
        # publish-helm-chart,operator,release-oss,release-plus,certify-openshift-images,aws-marketplace,azure-marketplace,gcp-marketplace,azure-upload,github-release,release-image-notification
        type: string
        required: false

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  # Disable operator release step for now until nginx-bot issue is resolved, manually trigger workflow in nginx-ingress-helm-operator
  operator:
    name: Trigger PR for Operator
    permissions:
      contents: write
      pull-requests: write
    uses: nginx/nginx-ingress-helm-operator/.github/workflows/sync-chart.yml@feat/update-version
    with:
      chart_version: ${{ inputs.chart_version }}
      operator_version: ${{ inputs.operator_version }}
      k8s_version: "1.33.1"
      dry_run: ${{ inputs.dry_run }}
